[package]
name = "envy"
description = "The environment manager you'll envy."
version = "0.1.0-dev"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.43", features = ["derive"] }
thiserror = "2.0.12"
